#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════
# PostgreSQL one-shot installer для Ubuntu 22.04 / 24.04
# ════════════════════════════════════════════════════════════════
# Что делает:
#   1. Ставит PostgreSQL (нативно, не в Docker — для прода так лучше:
#      проще бэкапы, быстрее, меньше абстракций)
#   2. Создаёт БД webMessanger и пользователя с заданным паролем
#   3. Настраивает pg_hba.conf на listen ТОЛЬКО на localhost
#      (наружу не торчит — доступ через SSH-туннель)
#   4. Создаёт каталог /var/backups/postgres для автобэкапов
#
# Использование:
#   sudo PG_PASSWORD='длинный_сложный_пароль' bash install.sh
#
# Дополнительные опции через env:
#   DB_NAME       — имя БД (по умолчанию webMessanger)
#   DB_USER       — имя пользователя (по умолчанию messanger)
#   PG_VERSION    — версия PG (по умолчанию 16, тек. LTS Ubuntu 24.04)

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
fail() { echo -e "${RED}[x]${NC} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "Запусти от root: sudo PG_PASSWORD='...' bash install.sh"

DB_NAME="${DB_NAME:-webMessanger}"
DB_USER="${DB_USER:-messanger}"
PG_VERSION="${PG_VERSION:-16}"

[[ -n "${PG_PASSWORD:-}" ]] || fail "PG_PASSWORD env-var обязателен. Пример: sudo PG_PASSWORD='ThePassw0rd!' bash install.sh"

# ─── Установка PostgreSQL ───────────────────────────────────────
if ! command -v psql &>/dev/null; then
    log "PostgreSQL не найден — ставлю..."
    apt-get update -y
    apt-get install -y postgresql postgresql-contrib
    log "PostgreSQL установлен ($(psql --version))"
else
    log "PostgreSQL уже установлен ($(psql --version))"
fi

# Имя service'а — зависит от версии
PG_SERVICE="postgresql"
systemctl enable --now "$PG_SERVICE"

# ─── Поиск конфига ──────────────────────────────────────────────
PG_CONF_DIR=$(sudo -u postgres psql -t -c "SHOW config_file;" | xargs dirname)
log "PostgreSQL config dir: $PG_CONF_DIR"

# ─── Создание БД и пользователя ─────────────────────────────────
log "Создаю пользователя $DB_USER и БД $DB_NAME..."

# Создаём пользователя (если ещё нет)
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" \
    | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER \"$DB_USER\" WITH PASSWORD '$PG_PASSWORD';"

# Меняем пароль если юзер уже был
sudo -u postgres psql -c "ALTER USER \"$DB_USER\" WITH PASSWORD '$PG_PASSWORD';"

# Создаём БД (если ещё нет)
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" \
    | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\";"

# Гарантируем права (на случай если БД создавалась до прав)
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"
sudo -u postgres psql -d "$DB_NAME" -c "GRANT ALL ON SCHEMA public TO \"$DB_USER\";"

log "БД $DB_NAME готова, владелец $DB_USER"

# Даём messanger полные права на схему public — чтобы Prisma migrate работал,
# и чтобы дамп от postgres-юзера можно было восстановить с нужным владением.
log "Расширяю привилегии $DB_USER на schema public..."
sudo -u postgres psql -d "$DB_NAME" <<EOF
ALTER SCHEMA public OWNER TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$DB_USER";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "$DB_USER";
GRANT USAGE, CREATE ON SCHEMA public TO "$DB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$DB_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$DB_USER";
EOF

# ─── Безопасность: listen только на localhost ───────────────────
PG_CONF="$PG_CONF_DIR/postgresql.conf"
PG_HBA="$PG_CONF_DIR/pg_hba.conf"

log "Настраиваю $PG_CONF — listen_addresses=localhost..."
# Меняем listen_addresses на localhost (если не было — добавим)
if grep -q "^listen_addresses" "$PG_CONF"; then
    sed -i "s|^listen_addresses.*|listen_addresses = 'localhost'|" "$PG_CONF"
else
    echo "listen_addresses = 'localhost'" >> "$PG_CONF"
fi

log "Настраиваю $PG_HBA — только локальные подключения..."
# Резервный бэкап исходного hba
cp -n "$PG_HBA" "${PG_HBA}.orig" 2>/dev/null || true

# Перезаписываем hba: localhost через md5, остальное — отрезаем
cat > "$PG_HBA" <<EOF
# ════════════════════════════════════════════════════════════════
# pg_hba.conf — auto-generated by install.sh
# ════════════════════════════════════════════════════════════════
# Сценарий доступа:
#   - локальные unix-socket подключения как ОС-юзер postgres → peer (для админских команд)
#   - локальные TCP/IP с 127.0.0.1 → md5 (приложение через SSH-туннель)
#   - всё остальное запрещено
# ════════════════════════════════════════════════════════════════

# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
local   all             all                                     md5
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
EOF

systemctl reload "$PG_SERVICE"
log "PostgreSQL перезагружен"

# ─── Каталог для бэкапов ────────────────────────────────────────
mkdir -p /var/backups/postgres
chown postgres:postgres /var/backups/postgres
chmod 700 /var/backups/postgres
log "Каталог /var/backups/postgres создан"

# ─── Финальный вывод ────────────────────────────────────────────
echo
echo "════════════════════════════════════════════════════════════════"
echo -e "${GREEN}PostgreSQL готов!${NC}"
echo "════════════════════════════════════════════════════════════════"
echo
echo "БД listen на: 127.0.0.1:5432 (НЕ открыт наружу)"
echo "База:    $DB_NAME"
echo "Юзер:    $DB_USER"
echo "Пароль:  *** (тот что вы передали в PG_PASSWORD)"
echo
echo "Доступ снаружи — только через SSH-туннель:"
echo "  ssh -L 5433:localhost:5432 root@<IP_VPS>"
echo "Тогда в .env:"
echo "  DATABASE_URL=postgresql://$DB_USER:<пароль>@localhost:5433/$DB_NAME?schema=public"
echo
echo "Для восстановления дампа:"
echo "  sudo -u postgres psql -d $DB_NAME < /tmp/dump.sql"
echo "════════════════════════════════════════════════════════════════"
